backend/controllers/PostController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Post;
use backend\models\PostSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends BaseController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Post();

        if ($model->load(Yii::$app->request->post())) {
            $model->file = UploadedFile::getInstance($model, 'photo');            
            
            if ($model->file)
            {
                $imageName = date('Ymdhis'). $model->file->baseName .'.'. $model->file->extension;
                $model->file->saveAs('../posts/' .$imageName);
                $model->photo = '/posts/' . $imageName;
            }
            $model->author_id = Yii::$app->user->identity->id;           
            
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $photo = $model->photo;

        if ($model->load(Yii::$app->request->post())) {
            $model->file = UploadedFile::getInstance($model, 'photo');            
            
            if ($model->file)
            {
                $imageName = date('Ymdhis'). $model->file->baseName .'.'. $model->file->extension;
                $model->file->saveAs('../posts/' .$imageName);
                $model->photo = '/posts/' . $imageName;
            } else {
                $model->photo = $photo;
            }
            $model->author_id = Yii::$app->user->identity->id;
            $model->save();
            
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                //    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {                
        if (!Yii::$app->user->isGuest) {
            $this->redirect(['site/index']);
        }

        $this->layout = 'login';
         
        $model = new LoginForm();        

        if ($model->load(Yii::$app->request->post())) {            
            
            $model->login();
            
            return $this->redirect(['site/index']);

        } else {
            // return var_dump($model);
            $model->password = '';
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionService()
    {
        return $this->render('services');
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionTeam()
    {
        return $this->render('team');
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionPortfolio()
    {
        return $this->render('portfolio');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use frontend\services\Collections;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>

  <div class="page-header">
            <div class="overlay">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1><?= Yii::t('app', 'О нас') ?></h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Header Section -->
        
        
        <!-- Start About Us Section -->
    <section id="about-section" class="about-section">
        <div class="container">
            <div class="row">
               <div class="col-md-5">
                   <div class="about-img">
                       <img src="/temp/images/corporate1.jpg" class="img-responsive" alt="About images">
                       <div class="head-text">                          
                       </div>
                   </div>
               </div>
               <div class="col-md-7">
                   <div class="about-text">
                       <p><?= Yii::t('app', "ZERONE - национальный разработчик программных решений в области информационной безопасности и управления персоналом. Мы разрабатываем программы по повышению эффективности коммерческих предприятий и государственных служб, направленные на снижение рисков, связанных с внутренними угрозами информационной безопасности. Продукция компании обеспечивает возможность мониторинга рабочих мест, анализа событий, контроля рабочего времени и производительности труда работников организаций, оповещения об опасных и непродуктивных действиях. Год назад мы начали разрабатывать нашу первую программу DLP, которая называется MSSDLP. Члены нашей команды молоды и имеют опыт работы более 5 лет на своих полях.") ?></p>
                   </div>                  
                   
               </div>                
            </div>
        </div>
    </section>
        
     
    <!-- Start Client Section -->
    <?php if(count(Collections::getClientsLogos()) > 0): ?>
        <div id="client-section" style="border-top: 1px solid #f1f1f1;">
            <div class="container">
                <div class="client-box">
                    <h2><?= Yii::t('app', "Наши клиенты"); ?></h2>
                    <section class="customer-logos slider">
                        <?php foreach (Collections::getClientsLogos() as $key => $value): ?> 
                            <div class="slide"><img src="<?= $value->logo ?>"></div>
                        <?php endforeach; ?>
                    </section>
                </div>                
            </div>
        </div>   
    <?php endif; ?>
    <?php $this->registerJsFile('https://code.jquery.com/jquery-2.2.4.min.js', ['position' => \yii\web\View::POS_HEAD]) ?>
    <?php $this->registerJsFile('https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.js', ['position' => \yii\web\View::POS_HEAD]) ?>
    <?php $this->registerJsFile('/slider/js/slider.js') ?>
    <?php $this->registerCssFile('/slider/css/main.css') ?>
    <!-- End Client Section -->
    
        
        

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">   
  <!-- Start Header Section -->
  <div class="page-header">
            <div class="overlay">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1><?= Yii::t('app', 'Связывайтесь с нами') ?></h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Header Section -->    

        <!-- Start Contact Us Section -->
    <section id="contact" class="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">   
                    <div class="about-list">
                       <h4><?= Yii::t('app', "Наш адрес"); ?></h4>
                       <ul>
                            <li><i class="fa fa-home"></i><?= Yii::t('app', "г. Ташкент, улица Мукимий, 3"); ?></li>
                            <li><i class="fa fa-phone"></i>+998 (90) 129-9977</li>
                            <li><i class="fa fa-envelope"></i><a href="#">info@zerone.uz</a></li>                            
                       </ul>
                       
                       <!-- <h4><?= Yii::t('app', "Страницы на соц. сетях"); ?></h4>
                       <ul>
                           <li><i class="fa fa-facebook"></i>Facebook</li>
                           <li><i class="fa fa-twitter"></i>Twitter</li>
                           <li><i class="fa fa-chrome"></i>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusan.</li>
                           <li><i class="fa fa-check-square"></i>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                       </ul> -->
                   </div>               
                </div>
                <div class="col-lg-8">                  
                    <div style="height: 400px" id="mapid"></div>
                </div>
            </div>            
        </div>
        
    </section>

    
    
    <?php $this->registerCssFile('https://unpkg.com/leaflet@1.4.0/dist/leaflet.css', [
        'integrity' => "sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA==",
        'crossorigin' => "", 
        // 'position' => \yii\web\View::POS_BEGIN
    ]) ?>
    <?php $this->registerJsFile('https://unpkg.com/leaflet@1.4.0/dist/leaflet.js', [
        'integrity' => "sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg==",
        'crossorigin' => "", 
        'position' => \yii\web\View::POS_HEAD
    ]) ?>

    <?php $this->registerJsFile('/js/map.js  ') ; ?>
   

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="container">

    <div class="alert alert-success" style="margin: 30px;">
        <?= nl2br(Html::encode($message)) ?>
    </div>

</div>

frontend/views/site/index.php
<?php

use frontend\services\Collections;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
 <!-- Start Header Section -->
<div class="banner">  
    <div class="overlay">
        <div class="container">
            <div class="intro-text">
                <h1>ZERONE<span></span></h1>
                <p><?= Yii::t('app', "Национальный разработчик программных решений в области обеспечения информационной безопасности и контроля действий персонала") ?></p>
                <a href="<?= Url::to(['/about']) ?>" class="page-scroll btn btn-primary"><?= Yii::t('app', 'Подробно') ?></a>
            </div>
        </div>            
    </div>
</div>
<!-- End Header Section -->
        
        
    <!-- Start Portfolio Section -->
    <section id="portfolio" class="portfolio-section-1">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title text-center wow fadeInDown" data-wow-duration="2s" data-wow-delay="50ms">
                        <h2><?= Yii::t('app', "Новости"); ?></h2>                        
                    </div>                        
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">                    
                    <!-- Start Portfolio items -->
                    <ul id="portfolio-list">
                        <?php foreach (Collections::getPosts() as $value): ?>                                                    
                            <li class="wow fadeInLeft" data-wow-duration="2s" data-wow-delay="300ms">                                
                                <a href="<?= Url::to(['post/view', 'id' => $value->id]) ?>" >                                
                                    <h3><?= $value->subject ?></h3>                                        
                                </a>
                                <div class="post-item">                                    
                                    <img src="<?= $value->photo; ?>" class="img-responsive" alt="" />                                        
                                    <div class="portfolio-caption">                                                                            
                                        <h4><?= Yii::t('app', "Подробно"); ?></h4>                                            
                                    </div>                                    
                                </div>                                
                            </li>                            
                        <?php endforeach; ?>                        
                    </ul>
                    <!-- End Portfolio items -->
                    <div class="btnnew">
                        <?= \yii\helpers\Html::a("Все новости", Url::to('post/index'), ['class' => 'btn btn-primary newsbtn']) ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Portfolio Section -->
        
    <!-- Start Service Section -->
    <section id="service-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title text-center wow fadeInDown" data-wow-duration="2s" data-wow-delay="50ms">
                        <h2><?= Yii::t('app', "Наши услуги"); ?></h2>                        
                    </div>                        
                </div>
            </div>
            <div class="row">                
                <?php foreach (Collections::getServices() as $key => $value): ?>                    
                    <div class="col-md-3">
                        <div class="services-post" id="index">
                            <a href="<?= Url::to(['/service', '#' => $key]) ?>"><i class="<?= $value->icon ?>"></i></a>
                            <?php if (Yii::$app->language == "ru"): ?>
                                <h2><?= $value->name_ru ?></h2>                            
                            <?php else: ?>
                                <h2><?= $value->name_uz ?></h2>                            
                            <?php endif; ?>
                        </div>
                    </div>                
                <?php endforeach; ?>                
            </div>
        </div>
    </section>
    <!-- Start Service Section -->
        
    <!-- Start Client Section -->
    <?php if(count(Collections::getClientsLogos()) > 0): ?>
    <!-- <div id="client-section" style="border-top: 1px solid #f1f1f1;">
        <div class="container">
            <div class="client-box">
                <div class="row">
                    <div class="col-md-12">
                        <div class="section-title text-center wow fadeInDown" data-wow-duration="2s" data-wow-delay="50ms">
                            <h2><?= Yii::t('app', "Наши клиенты"); ?></h2>                        
                        </div>                        
                    </div>
                </div>
                <section class="customer-logos slider">
                    <?php foreach (Collections::getClientsLogos() as $key => $value): ?> 
                        <div class="slide"><img src="<?= $value->logo ?>"></div>
                    <?php endforeach; ?>
                </section>
            </div>                
        </div>
    </div>    -->
    

    <?php $this->registerJsFile('https://code.jquery.com/jquery-2.2.4.min.js', ['position' => \yii\web\View::POS_HEAD]) ?>
    
    <?php endif; ?>

    <!-- End Client Section -->    

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>
                

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/portfolio.php
<?php

use yii\helpers\Url;
use frontend\services\Collections;


?>

 <div class="page-header">
            <div class="overlay">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1><?= Yii::t('app', 'Наши продукты') ?></h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Header Section -->       
        
        
        <!-- Start Portfolio Section -->
        <section id="portfolio" class="portfolio-section-2">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        
                        <!-- Start Portfolio items -->
                        <ul id="portfolio-list">
                            <?php foreach (Collections::getProducts() as $key => $value): ?> 
                                <li class="wow fadeInLeft" data-wow-duration="2s" data-wow-delay="300ms">
                                    <h3 class="" ><?= $value->name ?></h3>
                                    <a href="<?= Url::to(['product/view', 'id' => $value->id]) ?>">
                                        <div class="portfolio-item">
                                            <img src="<?= $value->icon; ?>" class="img-responsive" alt="" />
                                            <div class="portfolio-caption">
                                                <h4><?= $value->subheader_ru ?></h4>                                                                                        
                                            </div>
                                        </div>
                                    </a>
                                </li>                            
                            <?php endforeach; ?>
                        </ul>
                        <!-- End Portfolio items -->
                    </div>
                </div>
            </div>
        </section>
        <!-- End Portfolio Section -->
        

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>